server:
  port: 9001
spring:
  redis:
    shiro:
      host: 47.107.151.220
      port: 6379
      timeout: 2000
      password: pwd123
  datasource:
    name: biba-crm
    #UTF-8 ,不配置查询中文因为编码不一样查不到
#        url: jdbc:mysql://39.108.18.156:3306/biba_crm?characterEncoding=UTF-8&verifyServerCertificate=false&useSSL=true
    url: jdbc:mysql://127.0.0.1:3306/shiro?characterEncoding=UTF-8&verifyServerCertificate=false&useSSL=true
    username: root
    password: root
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20

#mybatis 全局配置
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.chason.springbootshiro.infrastructure.rbac.entity
  configuration:
    #开启驼峰命名
    map-underscore-to-camel-case: true
    #开启延迟加载
    lazy-loading-enabled: true
    aggressive-lazy-loading: false
    #开启二级缓存
    cache-enabled: true